cells/api/urls.py
from django.urls import path
from . import apiviews

app_name = 'cells_api'

urlpatterns = [
    path('login/',apiviews.Login.as_view(),name='login_api'),
    path('logout/',apiviews.Logout.as_view(),name='logout_api'),
    path('register/',apiviews.Register.as_view(),name='register_api'),
    path('show-items/',apiviews.ShowItems.as_view(),name='showitems_api'),
    path('detail/item/<int:pk>/',apiviews.DetailItem.as_view(),name='detail_item_api'),
    path('profile/',apiviews.Profile.as_view(),name='profile_api'),
    path('profile/show-items/',apiviews.ShowItemProfile.as_view(),name='profile_showitems_api'),
    path('item-profile/',apiviews.ItemProfile.as_view(),name='item_profile_api'),
    path('profile/change-password/',apiviews.ChangePassword.as_view(),name='change_password_api'),
    path('profile/changed-password/<uidb64>/<token>/',apiviews.TokenLinkRecived.as_view(),name='token_link_api'),
    path('restore-password/',apiviews.RestorePassword.as_view(),name='resotore_password_api')
]

cells/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'cells'

# urlpatterns

urlpatterns = [ 
    path('index/',views.index,name='index'),
    path('login/',views.LoginUser.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('register/',views.Register.as_view(),name='register'),
    path('register/changepassword/',views.ChangePasswordProfile.as_view(),name='change_password'),
    path('register/<uidb64>/<token>/',views.tokenLinkRecived,name='token_link'),
    path('restore/password/',views.RestorePassword.as_view(),name='restore_password'),
    path('shopping/',views.ShowItems.as_view(),name='dashboar_list'),
    path('shopping/<int:pk>/',views.DetailItem.as_view(),name='dashboar_detail'),
    path('create/item/',views.CreateItem.as_view(),name='create_item'),
    path('update/item/<int:pk>/',views.UpdateItem.as_view(),name='update_item'),
    path('delete/item/<int:pk>/',views.DeleteItem.as_view(),name='delete_item'),
    path('profile/',views.Profile.as_view(),name='profile'),
    path('update/profile/',views.UpdateProfile.as_view(),name='update_profile'),
    path('delete/profile/',views.DeleteProfile.as_view(),name='delete_profile'),
]

cells/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify

# ****************************************** Profile Model *****************************************************

class ProfileUserModel(models.Model):
    """
    Tabla de Registro de usuarios
    """
    user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name="profile")
    phone = models.CharField(max_length=8)
    created_date = models.DateTimeField(auto_now_add=True,db_index=True)
    updated_date = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='images/user/%Y/%m/%d',blank=True,null=True)
    address = models.CharField(max_length=200,null=True)

    class Meta:
        ordering = ['-created_date']
    
    
    def __str__(self) -> str:
        return f'Profile for user {self.user.username}'

   

# ************************************************* Shoping Model ***************************************************

class ShopCellModel(models.Model):
    """
    Tabla para el guardado de los articulos de venta
    """
    profile = models.ForeignKey(ProfileUserModel,on_delete=models.CASCADE,null=True,related_name='shopcell')
    model_name = models.CharField(max_length=150)
    slug = models.SlugField(max_length=150,blank=True,unique=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True,db_index=True)
    price = models.FloatField(max_length=6)
    image = models.ImageField(upload_to='images/smartphone/%Y/%m/%d',blank=True,null=True)
    description = models.TextField(max_length=1000,null=True)

    class Meta:
        ordering = ['-updated_date']
        
        
    def __str__(self) -> str:
        return f'Item cell {self.model_name}'
    

    def get_absolute_url(self):
        return reverse("cells:dashboar_detail", kwargs={'pk':self.pk})
    

    def save(self,*args, **kwargs) -> None:
        if not self.slug:
            self.slug = slugify(self.model_name +'-'+ str(self.profile.user.username))
        super().save(*args,**kwargs)

cells/forms.py
from django import forms
import re
from cells.models import ShopCellModel

#************************************** Login Form ***************************************************

# Login
class LoginForm(forms.Form):
    username = forms.CharField(max_length=25,required=True)
    password = forms.CharField(widget=forms.PasswordInput,max_length=12,required=True)

#************************************* Register Form *****************************************************

# User Registration
class UserRegistrationForm(forms.Form):
    username = forms.CharField(max_length=25,required=True)
    first_name = forms.CharField(max_length=50,required=True)
    last_name = forms.CharField(max_length=100,required=True)
    password = forms.CharField(widget=forms.PasswordInput,max_length=12,required=True)
    password2 = forms.CharField(widget=forms.PasswordInput,max_length=12,required=True)
    email = forms.EmailField(max_length=25)
    phone = forms.CharField(max_length=8,required=True)
    
    def clean_password2(self) -> str:
        cd = self.cleaned_data
        if (cd['password'] != cd['password2']):
            raise forms.ValidationError('Error keys')
        return cd['password2']
    
    def clean_phone(self) -> str:
        cd = self.cleaned_data
        pattern = re.compile("^5[1-8]")   
        if (len(cd['phone']) == 8) and pattern.search(cd['phone']) :
            return cd['phone']
        raise forms.ValidationError('Error phone number')
    

# Update User Form
class UpdateUserForm(forms.Form):
    username = forms.CharField(max_length=25,required=True)
    first_name = forms.CharField(max_length=50,required=True)
    last_name = forms.CharField(max_length=100,required=True)
    email = forms.EmailField(max_length=25)
    phone = forms.CharField(max_length=8,required=True)
    image = forms.ImageField(allow_empty_file=True)
    address = forms.CharField(max_length=200,required=True)

    def clean_phone(self) -> str:
        cd = self.cleaned_data
        pattern = re.compile("^5[1-8]")   
        if (len(cd['phone']) == 8) and pattern.search(cd['phone']):
            return cd['phone']
        raise forms.ValidationError('Error phone number')


# Delete User Form
class DeleteUserForm(forms.Form):
    delete = forms.CharField(widget=forms.CheckboxInput)


# Change Password User
class ChangePasswordForm(forms.Form):
    currentpassword = forms.CharField(widget=forms.PasswordInput,max_length=12,required=True)
    newpassword = forms.CharField(widget=forms.PasswordInput,max_length=12,required=True)
    confirmpassword = forms.CharField(widget=forms.PasswordInput,max_length=12,required=True)

    def clean(self) -> str:
        cd = self.cleaned_data
        if cd['currentpassword'] != cd['newpassword'] and cd['newpassword'] == cd['confirmpassword']:
            return cd 
        raise forms.ValidationError('Error keys')


# Restore Password User
class RestorePassowrdForm(forms.Form):
    email = forms.EmailField(max_length=25)


#********************************************* Items Forms ****************************************************

# Items Form
class DeleteItemForm(forms.Form):
    delete = forms.CharField(widget=forms.CheckboxInput)


class UpdateItemForm(forms.ModelForm):
    
    class Meta:
        model = ShopCellModel
        fields = ['model_name','price','image','description']

    

cells/views.py
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.contrib.sites.shortcuts import get_current_site
from django.utils.decorators import method_decorator
from django.views.generic import View
from django.contrib.sessions.models import Session
from django.http import HttpResponse
from .forms import (LoginForm, UserRegistrationForm, DeleteItemForm, UpdateItemForm,
                    DeleteUserForm, UpdateUserForm, ChangePasswordForm, RestorePassowrdForm)
from .models import ShopCellModel, ProfileUserModel
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from threading import Thread
import re
import datetime

# ************************************* Email tool ************************************************

# Send Email


def sendEmail(subject: str, message: dict, recipient_list: str, name_thred: str) -> None:
    """Send email, send an email to user en case of changes in your account

    Args:
        subject (str): subject
        message (dict): message
        recipient_list (str): recipient
        name_thred (str): name of the thred (It uses username)
    """

    thred = Thread(target=send_mail, args=[
        subject, message, 'procode@example.com', [recipient_list], True], name=name_thred)
    thred.start()


# **************************************** Function Views ************************************************

def index(request: str) -> HttpResponse:
    """
    Index (home) presentation page
       

    Args:
        request (str): HTTP request

    Returns:
        Object: HTTP response
    """
    return render(request, 'cell_index.html')


def page_400_bad_request(request: str, exception: object, template_name='errors/400.html') -> HttpResponse:
    return render(request, template_name)


def page_403_not_acces(request: str, exception: object, template_name='errors/403.html') -> HttpResponse:
    return render(request, template_name)


def page_404_not_found(request: str, exception: object, template_name='errors/404.html') -> HttpResponse:
    return render(request, template_name)


def page_500_error(request: str, template_name='errors/500.html') -> HttpResponse:
    return render(request, template_name)

# ********************************************* Login View ***********************************************

# Login (Register)


class LoginUser(View):
    """
    Login view, view for login user

    Args:
        View (object): View class

    Returns:
        Object: HTTP response
    """
    template_name = 'accounts/registration/login.html'
    form_class = LoginForm
    context_object_name = 'form'
    queryset = Session.objects.all()

    def get(self, request: str, *args, **kwargs) -> HttpResponse:
        form = self.form_class()
        return render(request, self.template_name, {self.context_object_name: form})

    def post(self, request: str, *args, **kwargs) -> HttpResponse:
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request, username=cd['username'], password=cd['password'])
            if user is not None:
                all_sessions = self.queryset.filter(expire_date__gte = datetime.datetime.now())
                for session in all_sessions:
                    session_id = session.get_decoded()
                    if user.id == int(session_id.get('_auth_user_id')):
                        session.delete()
                        messages.add_message(request, level=messages.WARNING,
                                             message='Se intentó una doble sesión')
                        return render(request, self.template_name, {self.context_object_name: form})
                login(request, user=user)
                return HttpResponse('302')
            messages.add_message(request, level=messages.INFO,
                                 message='Usuario no activo o credenciales incorrectas')
        return render(request, self.template_name, {self.context_object_name: form})


# ******************************************* Register Views **************************************************

# Register (Register)
class Register(View):
    """
    Register view, view for registering user

    Args:
        View (object): View class

    Returns:
        Object: HTTP response
    """
    template_name = 'accounts/registration/register.html'
    form_class = UserRegistrationForm
    context_object_name = 'form'
    model = User

    def get(self, request: str, *args, **kwargs) -> HttpResponse:
        form = self.form_class()
        return render(request, self.template_name, {self.context_object_name: form})

    def post(self, request: str, *args, **kwargs) -> HttpResponse:
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if not self.model.objects.filter(email=cd['email']).exists():
                new_user = self.model()
                new_user.username = cd['username']
                new_user.set_password(cd['password'])
                new_user.first_name = cd['first_name']
                #new_user.is_active = False
                new_user.last_name = cd['last_name']
                new_user.email = cd['email']
                # email_sender
                try:
                    new_user.save()
                    ProfileUserModel.objects.create(
                        user=new_user, phone=cd['phone'])
                    # email
                    subject = 'ProC0d3 Registro de usuario'
                    message = render_to_string('email/email_register.html', {
                        'domain': get_current_site(request),
                        'user': new_user.username,
                        'uid': urlsafe_base64_encode(force_bytes(new_user.pk)),
                        'token': default_token_generator.make_token(new_user),
                        'protocol': request.scheme,
                    })
                    #sendEmail(subject, message, cd['email'], new_user.username)
                    messages.add_message(
                        request, level=messages.SUCCESS, message='Registro completado.')
                    # redireccion
                    return HttpResponse('302')
                except:
                    messages.add_message(
                        request, level=messages.WARNING, message='El nombre de usuario ya existe')
            else:
                messages.add_message(
                    request, level=messages.WARNING, message='El e-mail ya existe en nuestro sistema')
        return render(request, self.template_name, {self.context_object_name: form})


# Registration succefull  (Register)
def tokenLinkRecived(request: str, uidb64: bytes, token: str) -> HttpResponse:
    """
    Token link recived, function for reciving token

    Args:
        request (str): HTTP request
        uidb64 (bytes): urls base 64 encoder
        token (str): _description_

    Returns:
        Objecte: HTTP response
    """
    try:
        pk = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=pk)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if (user is not None and default_token_generator.check_token(user, token)):
        user.is_active = True
        user.save()
    else:
        return render(request, 'dashboard/token_fail.html')
    messages.add_message(request, level=messages.SUCCESS,
                         message='Ya puede entrar a su cuenta')
    return redirect('cells:index')


# **************************************** Dashboard Views **********************************************

# List Items (Dashboard)
class ShowItems(View):
    """Show items, view for showing items

    Args:
        View (object): View class

    Returns:
        Object: HTTP response
    """
    template_name = 'dashboard/cell_items.html'
    model = ShopCellModel
    context_object_name = 'itemcells'

    def get(self, request: str, *args, **kwargs) -> HttpResponse:
        is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
        search = request.GET.get('search')
        page = request.GET.get('page')
        # Sanetizando la busqueda
        pattern = re.compile("[a-zA-Z0-9\s]+")
        if search is not None and pattern.search(search):
            items = self.model.objects.defer(
                'created_date', 'description', 'slug').filter(model_name__icontains=search)
        else:
            items = self.model.objects.defer(
                'created_date', 'description', 'slug').all()
        paginator = Paginator(items, 15)
        try:
            items = paginator.page(page)
        except PageNotAnInteger:
            items = paginator.page(1)
        except EmptyPage:
            if is_ajax:
                return HttpResponse('')
            items = paginator.page(paginator.num_pages)
        if is_ajax:
            return render(request, 'dashboard/items_ajax.html', {self.context_object_name: items})
        return render(request, self.template_name, {self.context_object_name: items})


# Detail Items (Dashboard)
class DetailItem(View):
    """
    Detail item, view for showing detail items

    Args:
        View (object): View class

    Returns:
        Object: HTTP response
    """
    template_name = 'dashboard/item_detail.html'
    model = ShopCellModel
    context_object_name = 'itemcell'

    def get(self, request: str, *args, **kwargs) -> HttpResponse:

cells/templates/accounts/profile/cell_profile.html
{% extends 'cell_index.html' %}
{% block title %}User profile{% endblock title %}
{% load static %}
{% load cloudinary %}
{% cloudinary test_model_instance.image.name width=100 height=100 %}
{% block content %}
<section class="bg-profile">
    <div style="height: 5rem;"></div>
    <div class="d-lg-flex d-md-block d-sm-block  gap-3">
        <!--Column 1-->
        <div class="container">
            {% if messages %}
            <!--Message-->
            {% for mess in messages %}
            <div class="alert alert-{{mess.tags|lower}} success alert-dismissible fade show box-alert-transition"
                role="alert">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                    class="bi bi-check-circle-fill" viewBox="0 0 16 16">
                    <path
                        d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
                </svg>
                {{ mess }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            {% endif %}
            <!--User information-->
            <div class="card mb-3 text-light border-0 bg-transparent shadow">
                <div class="d-lg-flex d-md-flex d-sm-block gap-3 card-bg">
                    <div class="p-4">
                        <img src=" {% if user.profile.image %} {{ user.profile.image.url }} {% else %} '' {% endif %}"
                            class="img-thumbnail rounded-circle p-2 bg-transparent" alt="No picture">
                    </div>
                    <div class="p-2">
                        <div class="card-body  ">
                            <h5 class="card-title"> {{ user.username }} </h5>
                            <p class="card-text">Name: {{ user.first_name }} </p>
                            <p class="card-text">Last name: {{ user.last_name }} </p>
                            <p class="card-text">Address: {{ user.profile.address }} </p>
                            <p class="card-text">Phone: {{ user.profile.phone }} </p>
                            <p class="card-text">E-mail: {{ user.email }} </p>
                            <p class="card-text"><small class="text-light">
                                    Member of: {{ user.profile.created_date|timesince }} <br>
                                    Last visit: {{ user.profile.updated_date|timesince }} <br>
                                </small></p>
                        </div>
                    </div>
                </div>
                <!--Vertical navbar-->
                <ul class="nav flex-column  bg-verticalsearch p-4">
                    <li class="nav-item p-2">
                        <a href=" {% url 'cells:create_item' %} " class="nav-link zoon text-white">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="white"
                                class="bi bi-boxes" viewBox="0 0 16 16">
                                <path
                                    d="M7.752.066a.5.5 0 0 1 .496 0l3.75 2.143a.5.5 0 0 1 .252.434v3.995l3.498 2A.5.5 0 0 1 16 9.07v4.286a.5.5 0 0 1-.252.434l-3.75 2.143a.5.5 0 0 1-.496 0l-3.502-2-3.502 2.001a.5.5 0 0 1-.496 0l-3.75-2.143A.5.5 0 0 1 0 13.357V9.071a.5.5 0 0 1 .252-.434L3.75 6.638V2.643a.5.5 0 0 1 .252-.434L7.752.066ZM4.25 7.504 1.508 9.071l2.742 1.567 2.742-1.567L4.25 7.504ZM7.5 9.933l-2.75 1.571v3.134l2.75-1.571V9.933Zm1 3.134 2.75 1.571v-3.134L8.5 9.933v3.134Zm.508-3.996 2.742 1.567 2.742-1.567-2.742-1.567-2.742 1.567Zm2.242-2.433V3.504L8.5 5.076V8.21l2.75-1.572ZM7.5 8.21V5.076L4.75 3.504v3.134L7.5 8.21ZM5.258 2.643 8 4.21l2.742-1.567L8 1.076 5.258 2.643ZM15 9.933l-2.75 1.571v3.134L15 13.067V9.933ZM3.75 14.638v-3.134L1 9.933v3.134l2.75 1.571Z" />
                            </svg>
                            Create</a>
                    </li>
                    <li class="nav-item p-2">
                        <a href=" {% url 'cells:update_profile' %} " class="nav-link zoon text-white">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="white"
                                class="bi bi-file-person" viewBox="0 0 16 16">
                                <path
                                    d="M12 1a1 1 0 0 1 1 1v10.755S12 11 8 11s-5 1.755-5 1.755V2a1 1 0 0 1 1-1h8zM4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H4z" />
                                <path d="M8 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                            </svg>
                            Update</a>
                    </li>
                    <li class="nav-item p-2">
                        <a class="nav-link zoon text-white" id="deleteprofile" data-bs-toggle="modal"
                            data-bs-target="#modalblock" onclick=deleteprofile()>
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="white"
                                class="bi bi-file-person" viewBox="0 0 16 16">
                                <path
                                    d="M12 1a1 1 0 0 1 1 1v10.755S12 11 8 11s-5 1.755-5 1.755V2a1 1 0 0 1 1-1h8zM4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H4z" />
                                <path d="M8 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                            </svg>
                            Delete
                        </a>
                    </li>
                    <li class="nav-item p-2">
                        <a class="nav-link zoon text-white" id="changepassword" data-bs-toggle="modal"
                            data-bs-target="#modalblock">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="white"
                                class="bi bi-fingerprint" viewBox="0 0 16 16">
                                <path
                                    d="M8.06 6.5a.5.5 0 0 1 .5.5v.776a11.5 11.5 0 0 1-.552 3.519l-1.331 4.14a.5.5 0 0 1-.952-.305l1.33-4.141a10.5 10.5 0 0 0 .504-3.213V7a.5.5 0 0 1 .5-.5Z" />
                                <path
                                    d="M6.06 7a2 2 0 1 1 4 0 .5.5 0 1 1-1 0 1 1 0 1 0-2 0v.332c0 .409-.022.816-.066 1.221A.5.5 0 0 1 6 8.447c.04-.37.06-.742.06-1.115V7Zm3.509 1a.5.5 0 0 1 .487.513 11.5 11.5 0 0 1-.587 3.339l-1.266 3.8a.5.5 0 0 1-.949-.317l1.267-3.8a10.5 10.5 0 0 0 .535-3.048A.5.5 0 0 1 9.569 8Zm-3.356 2.115a.5.5 0 0 1 .33.626L5.24 14.939a.5.5 0 1 1-.955-.296l1.303-4.199a.5.5 0 0 1 .625-.329Z" />
                                <path
                                    d="M4.759 5.833A3.501 3.501 0 0 1 11.559 7a.5.5 0 0 1-1 0 2.5 2.5 0 0 0-4.857-.833.5.5 0 1 1-.943-.334Zm.3 1.67a.5.5 0 0 1 .449.546 10.72 10.72 0 0 1-.4 2.031l-1.222 4.072a.5.5 0 1 1-.958-.287L4.15 9.793a9.72 9.72 0 0 0 .363-1.842.5.5 0 0 1 .546-.449Zm6 .647a.5.5 0 0 1 .5.5c0 1.28-.213 2.552-.632 3.762l-1.09 3.145a.5.5 0 0 1-.944-.327l1.089-3.145c.382-1.105.578-2.266.578-3.435a.5.5 0 0 1 .5-.5Z" />
                                <path
                                    d="M3.902 4.222a4.996 4.996 0 0 1 5.202-2.113.5.5 0 0 1-.208.979 3.996 3.996 0 0 0-4.163 1.69.5.5 0 0 1-.831-.556Zm6.72-.955a.5.5 0 0 1 .705-.052A4.99 4.99 0 0 1 13.059 7v1.5a.5.5 0 1 1-1 0V7a3.99 3.99 0 0 0-1.386-3.028.5.5 0 0 1-.051-.705ZM3.68 5.842a.5.5 0 0 1 .422.568c-.029.192-.044.39-.044.59 0 .71-.1 1.417-.298 2.1l-1.14 3.923a.5.5 0 1 1-.96-.279L2.8 8.821A6.531 6.531 0 0 0 3.058 7c0-.25.019-.496.054-.736a.5.5 0 0 1 .568-.422Zm8.882 3.66a.5.5 0 0 1 .456.54c-.084 1-.298 1.986-.64 2.934l-.744 2.068a.5.5 0 0 1-.941-.338l.745-2.07a10.51 10.51 0 0 0 .584-2.678.5.5 0 0 1 .54-.456Z" />
                                <path
                                    d="M4.81 1.37A6.5 6.5 0 0 1 14.56 7a.5.5 0 1 1-1 0 5.5 5.5 0 0 0-8.25-4.765.5.5 0 0 1-.5-.865Zm-.89 1.257a.5.5 0 0 1 .04.706A5.478 5.478 0 0 0 2.56 7a.5.5 0 0 1-1 0c0-1.664.626-3.184 1.655-4.333a.5.5 0 0 1 .706-.04ZM1.915 8.02a.5.5 0 0 1 .346.616l-.779 2.767a.5.5 0 1 1-.962-.27l.778-2.767a.5.5 0 0 1 .617-.346Zm12.15.481a.5.5 0 0 1 .49.51c-.03 1.499-.161 3.025-.727 4.533l-.07.187a.5.5 0 0 1-.936-.351l.07-.187c.506-1.35.634-2.74.663-4.202a.5.5 0 0 1 .51-.49Z" />
                            </svg>
                            Password
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <!--Column 2-->
        <!--Items block-->
        <div class="container">
            <form class=" bg-transparent" method="GET" action="">
                <input class="form-control me-2 shadow" id="id-search" onkeydown=takeKeypress(event) type="search"
                    placeholder="Buscar..." aria-label="Search" name="search">
            </form>
            <div class="row p-2 text-light"
                style="height: 50rem;overflow:scroll" id="items-ajax" onscroll=scrollInf()>
                {% include 'accounts/profile/user_items_list.html' %}
            </div>
        </div>
    </div>
    <div style="height: 10rem;"></div>
</section>
{% endblock content %}

{% block script %}
<script src=" {% static 'procodejs/scrollitems.js' %} "></script>
<script src=" {% static 'procodejs/selectorGet.js' %} "></script>
<script src=" {% static 'procodejs/selectorPost.js' %} "></script>
{% endblock script %}

cells/templates/accounts/profile/profile.html
{% extends 'base.html' %}